{
  programs.fish.shellAbbrs = {
    "ga." = "git add .";
    "gr." = "git restore .";
    g = "git";
    ga = "git add";
    gap = "git add -p";
    gb = "git branch";
    gbd = "git branch -d";
    gbD = "git branch -D";
    gbl = "git blame";
    gc = "git commit -m";
    gca = "git commit --amend";
    gcf = "git clean -f .";
    gcl = "git clone";
    gco = "git checkout";
    gcob = "git checkout -b";
    gd = "git diff";
    gdc = "git diff --compact-summary";
    gds = "git diff --staged";
    gl = "git log";
    gp = "git push";
    gpa = "git push --all";
    gpf = "git push --force-with-lease";
    gpl = "git pull";
    gpo = "git push origin";
    gpod = "git push origin --delete";
    gps = "git push -u origin";
    gr = "git restore";
    grb = "git rebase -i";
    grbc = "git rebase --continue";
    grh = "git reset HEAD";
    grp = "git restore -p";
    grv = "git revert";
    gs = "git show";
    gst = "git status";
    gsw = "git switch";
  };
}
