name: Build
on:
  push:
    paths:
      - flake.lock
  workflow_dispatch:

jobs:
  build-nixos:
    name: NixOS
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - host: NixBtw
          - host: Rescanix

    steps:
      - name: Set up directories
        run: |
          sudo mkdir /nix
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /home/linuxbrew
          sudo rm -rf /home/runner/.rustup
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/lib/heroku
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /var/lib/docker/overlay2

      - name: Maximize disk space
        uses: easimon/maximize-build-space@v8
        with:
          swap-size-mb: 4096
          build-mount-path: /nix
          overprovision-lvm: "true"
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra-conf: |
            log-lines = 500

      - name: Set up Attic
        uses: ErrorNoInternet/attic-action@v0
        with:
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: "${{ secrets.ATTIC_TOKEN }}"

      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: errornobinaries
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - uses: actions/checkout@v4

      - name: "Build for ${{ matrix.host }} (NixOS)"
        run: nix build -j 2 --cores 2 .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
