name: Check
on:
  push:
    paths:
      - '**.nix'
      - flake.lock
  pull_request:
  workflow_dispatch:

jobs:
  nix-flake:
    name: Nix flake
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: |
            log-lines = 500

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          fail-mode: true
          check-outdated: false

      - name: Check Nix flake outputs
        run: nix flake check --all-systems --show-trace
      
      - name: Check ErrorNoPhone (nix-on-droid)
        run: nix build --dry-run --impure \
               --option extra-substituters "https://nix-on-droid.cachix.org" \
               --option extra-trusted-public-keys "nix-on-droid.cachix.org-1:56snoMJTXmDRC1Ei24CmKoUqvHJ9XCp+nidK7qkMQrU=" \
               .#nixOnDroidConfigurations.ErrorNoPhone.activationPackage
