name: Lint
on:
  push:
    paths:
      - '**.nix'
      - flake.lock
  pull_request:
  workflow_dispatch:

jobs:
  nix-expressions:
    name: Nix expressions
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: |
            log-lines = 500

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Check if properly formatted
        run: nix run nixpkgs#nixfmt-rfc-style -- -c .

      - name: Run static code analysis
        if: always()
        run: nix run nixpkgs#statix -- check

      - name: Scan for dead code
        if: always()
        run: nix run nixpkgs#deadnix -- -f

      - name: Check if inputs are sorted
        if: always()
        run: nix-instantiate --eval library/check-inputs-sorted.nix
