name: Lint
on:
  push:
    paths:
      - flake.nix
      - droid/**
      - home/**
      - packages/**
      - secrets/**
      - server/**
      - shared/**
      - workstation/**
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    name: Code
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra-conf: |
            log-lines = 500

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Check formatting
        run: nix run nixpkgs#alejandra -- -c .

      - name: Check for dead code
        if: always()
        run: nix run nixpkgs#deadnix -- -f
