name: Nix Checks
on:
  push:
    paths:
      - home-manager/**
      - nix-on-droid/**
      - packages/**
      - server/**
      - workstation/**
      - flake.nix
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    name: Check Nix flake
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes

      - name: Check formatting
        run: nix-shell -p alejandra --run "alejandra -c ."

      - name: Check all flake outputs
        if: always()
        run: nix flake check --all-systems
